
package com.ventplan.prinzipskizze.wsclient.wac237;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PrinzipskizzeWAC237", targetNamespace = "http://service.ventplan.com/prinzipskizze/wac237", wsdlLocation = "http://localhost:8080/ventplan237/PrinzipskizzeWAC237?wsdl")
public class PrinzipskizzeWAC237_Service
    extends Service
{

    private final static URL PRINZIPSKIZZEWAC237_WSDL_LOCATION;
    private final static WebServiceException PRINZIPSKIZZEWAC237_EXCEPTION;
    private final static QName PRINZIPSKIZZEWAC237_QNAME = new QName("http://service.ventplan.com/prinzipskizze/wac237", "PrinzipskizzeWAC237");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ventplan237/PrinzipskizzeWAC237?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRINZIPSKIZZEWAC237_WSDL_LOCATION = url;
        PRINZIPSKIZZEWAC237_EXCEPTION = e;
    }

    public PrinzipskizzeWAC237_Service() {
        super(__getWsdlLocation(), PRINZIPSKIZZEWAC237_QNAME);
    }

    public PrinzipskizzeWAC237_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns WAC237Service
     */
    @WebEndpoint(name = "WAC237ServicePort")
    public WAC237Service getWAC237ServicePort() {
        return super.getPort(new QName("http://service.ventplan.com/prinzipskizze/wac237", "WAC237ServicePort"), WAC237Service.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WAC237Service
     */
    @WebEndpoint(name = "WAC237ServicePort")
    public WAC237Service getWAC237ServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ventplan.com/prinzipskizze/wac237", "WAC237ServicePort"), WAC237Service.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRINZIPSKIZZEWAC237_EXCEPTION!= null) {
            throw PRINZIPSKIZZEWAC237_EXCEPTION;
        }
        return PRINZIPSKIZZEWAC237_WSDL_LOCATION;
    }

}
