
package com.ventplan.prinzipskizze.wsclient.wac237;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WAC237Service", targetNamespace = "http://service.ventplan.com/prinzipskizze/wac237")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WAC237Service {


    /**
     * 
     * @param projekt
     * @param aussenluft
     * @param zuluft1
     * @param zuluft3
     * @param abluft1
     * @param zuluft2
     * @param abluft2
     * @param dokumentersteller
     * @param fortluft
     * @param abluft3
     * @param plan
     * @param erstelldatum
     * @param zentralgerat
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "prinzipskizzeWAC237", targetNamespace = "http://service.ventplan.com/prinzipskizze/wac237", className = "com.ventplan.prinzipskizze.wsclient.wac237.PrinzipskizzeWAC237")
    @ResponseWrapper(localName = "prinzipskizzeWAC237Response", targetNamespace = "http://service.ventplan.com/prinzipskizze/wac237", className = "com.ventplan.prinzipskizze.wsclient.wac237.PrinzipskizzeWAC237Response")
    public byte[] prinzipskizzeWAC237(
        @WebParam(name = "projekt", targetNamespace = "")
        String projekt,
        @WebParam(name = "plan", targetNamespace = "")
        String plan,
        @WebParam(name = "dokumentersteller", targetNamespace = "")
        String dokumentersteller,
        @WebParam(name = "erstelldatum", targetNamespace = "")
        String erstelldatum,
        @WebParam(name = "aussenluft", targetNamespace = "")
        String aussenluft,
        @WebParam(name = "fortluft", targetNamespace = "")
        String fortluft,
        @WebParam(name = "zentralgerat", targetNamespace = "")
        String zentralgerat,
        @WebParam(name = "abluft1", targetNamespace = "")
        List<String> abluft1,
        @WebParam(name = "abluft2", targetNamespace = "")
        List<String> abluft2,
        @WebParam(name = "abluft3", targetNamespace = "")
        List<String> abluft3,
        @WebParam(name = "zuluft1", targetNamespace = "")
        List<String> zuluft1,
        @WebParam(name = "zuluft2", targetNamespace = "")
        List<String> zuluft2,
        @WebParam(name = "zuluft3", targetNamespace = "")
        List<String> zuluft3);

}
