
package com.ventplan.prinzipskizze.wsclient.wac202;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PrinzipskizzeService", targetNamespace = "http://service.ventplan.com/prinzipskizze", wsdlLocation = "http://localhost:8080/ventplan237/PrinzipskizzeService?wsdl")
public class PrinzipskizzeService
    extends Service
{

    private final static URL PRINZIPSKIZZESERVICE_WSDL_LOCATION;
    private final static WebServiceException PRINZIPSKIZZESERVICE_EXCEPTION;
    private final static QName PRINZIPSKIZZESERVICE_QNAME = new QName("http://service.ventplan.com/prinzipskizze", "PrinzipskizzeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ventplan237/PrinzipskizzeService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRINZIPSKIZZESERVICE_WSDL_LOCATION = url;
        PRINZIPSKIZZESERVICE_EXCEPTION = e;
    }

    public PrinzipskizzeService() {
        super(__getWsdlLocation(), PRINZIPSKIZZESERVICE_QNAME);
    }

    public PrinzipskizzeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns WAC202Service
     */
    @WebEndpoint(name = "PrinzipskizzePort")
    public WAC202Service getPrinzipskizzePort() {
        return super.getPort(new QName("http://service.ventplan.com/prinzipskizze", "PrinzipskizzePort"), WAC202Service.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WAC202Service
     */
    @WebEndpoint(name = "PrinzipskizzePort")
    public WAC202Service getPrinzipskizzePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.ventplan.com/prinzipskizze", "PrinzipskizzePort"), WAC202Service.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRINZIPSKIZZESERVICE_EXCEPTION!= null) {
            throw PRINZIPSKIZZESERVICE_EXCEPTION;
        }
        return PRINZIPSKIZZESERVICE_WSDL_LOCATION;
    }

}
