
package com.ventplan.prinzipskizze.wsclient.wac202;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WAC202Service", targetNamespace = "http://service.ventplan.com/prinzipskizze")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WAC202Service {


    /**
     * 
     * @param zuluft3
     * @param zuluft2
     * @param abluft1
     * @param abluft2
     * @param abluft3
     * @param fortluft
     * @param aussenluft
     * @param zuluft1
     * @param zentralgerat
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "prinzipskizze", targetNamespace = "http://service.ventplan.com/prinzipskizze", className = "com.ventplan.prinzipskizze.wsclient.wac202.Prinzipskizze")
    @ResponseWrapper(localName = "prinzipskizzeResponse", targetNamespace = "http://service.ventplan.com/prinzipskizze", className = "com.ventplan.prinzipskizze.wsclient.wac202.PrinzipskizzeResponse")
    public byte[] prinzipskizze(
        @WebParam(name = "aussenluft", targetNamespace = "")
        String aussenluft,
        @WebParam(name = "fortluft", targetNamespace = "")
        String fortluft,
        @WebParam(name = "zentralgerat", targetNamespace = "")
        String zentralgerat,
        @WebParam(name = "abluft1", targetNamespace = "")
        List<String> abluft1,
        @WebParam(name = "abluft2", targetNamespace = "")
        List<String> abluft2,
        @WebParam(name = "abluft3", targetNamespace = "")
        List<String> abluft3,
        @WebParam(name = "zuluft1", targetNamespace = "")
        List<String> zuluft1,
        @WebParam(name = "zuluft2", targetNamespace = "")
        List<String> zuluft2,
        @WebParam(name = "zuluft3", targetNamespace = "")
        List<String> zuluft3);

}
